### ISSUE TITLE
I'm new to blazegraph, could you clarify?

### ISSUE THREAD

**Issue by Olivier4477** [blazegraph/database#203]
Hello,

I discover blazegraph. I want to use government data for an app.

However, the data (.rdf) is very big (3.30go)
For example, if I do:
curl -X POST -H "Content-Type: application / rdf + xml" --data-binary @ flux.rdf "http: // localhost: 9999 / blazegraph / namespace / kb / sparql"

Blazegraph takes about 2 hours to load the data. When I wrote to you, I did:
curl -X POST http: // localhost: 9999 / blazegraph / namespace / kb / sparql --data-urlencode 'update = DROP ALL'

Obviously the drop time is also very long.

Knowing that the data (.rdf) is updated every day, how can I update blazegraph? Is it possible to update blazegraph without deleting (drop all)?

How can I speed up the upload / update of data?

Thanking you

Have a good day

**Comment by thompsonbry** [comment]
The easiest is to run two instances (ideally on two machines). Load into
one in the background, cut over once loaded, then delete the journal on the
other instance and start your next load there.

**Comment by Olivier4477** [comment]
thank you for your reply.

But I already have to use a minimum 8GB machine for blazegraph to work ...
If I have to use a second it is not the same budget.

Is it really the only solution?

It is not possible for example:
curl -X POST -H "Content-Type: application / rdf + xml" --data-binary @ flux.rdf "http: // localhost: 9999 / blazegraph / namespace / kb / sparql"
to specify a table name (example current date)
at midnight load the update (with the new name of the table) and delete the table from the days before?

Or another possibility?

I really want to use the data the government provides me but it's RDF / sparql ...

thank you so much

**Comment by Olivier4477** [comment]
Ok I think I understood your logic, but to put it into practice I will need help.

I'll explain, I use a docker-compose like this:

```
version: '3.1'

services:

    blazegraph:
        image: conjecto/blazegraph:2.1.5
        restart: always
        ports:
          - 9999:9999
        environment:
            JAVA_OPTS: "-Xms2g -Xmx3g"
        volumes:
          - ./dataset:/docker-entrypoint-initdb.d

    datatourisme:
        build: docker
        ports:
            - "8080:80"
        restart: always
        depends_on:
            - blazegraph

```
This image is provided in government documentation for data usage.

So for the moment I do:
docker-compose up
then I load the data like this:
curl -X POST -H "Content-Type: application / rdf + xml" --data-binary @ flux.rdf "http: // localhost: 9999 / blazegraph / namespace / kb / sparql"
(the data file must be stored in dataset / kb / data

Then, if I want to reload I must:
docker-compose rm blazegraph
then docker system plum
then relaunch blazegraph

This is how I proceed now.

Before this solution, I used apache java Jena for sparql, it took 5 hours to load the data (on my computer 32 gb of ram)
